// Code generated by protoc-gen-go.
// source: errId.proto
// DO NOT EDIT!

package luatest

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ErrId int32

const (
	ErrId_OK                 ErrId = 0
	ErrId_UnknownError       ErrId = 1
	ErrId_UnPackError        ErrId = 2
	ErrId_SystemError        ErrId = 3
	ErrId_CustomError        ErrId = 4
	ErrId_ModelClose         ErrId = 5
	ErrId_AccountExist       ErrId = 100
	ErrId_AccountNotFound    ErrId = 101
	ErrId_PasswordError      ErrId = 102
	ErrId_KickOff            ErrId = 103
	ErrId_AccountIllegal     ErrId = 104
	ErrId_RoleNotOnline      ErrId = 105
	ErrId_NicknameExist      ErrId = 106
	ErrId_AccountTempExist   ErrId = 107
	ErrId_RoleNotExist       ErrId = 108
	ErrId_AccountLoging      ErrId = 109
	ErrId_InstanceNotExist   ErrId = 200
	ErrId_InstanceNotSingle  ErrId = 201
	ErrId_InstanceNotMutli   ErrId = 202
	ErrId_InstanceNotUnlock  ErrId = 203
	ErrId_CreateTeamError    ErrId = 300
	ErrId_TeamFullError      ErrId = 301
	ErrId_TeamDismiss        ErrId = 302
	ErrId_TeamInInstance     ErrId = 303
	ErrId_ItemNumNotEnough   ErrId = 400
	ErrId_MailNotExist       ErrId = 450
	ErrId_ReqFriendEnough    ErrId = 500
	ErrId_WeaponNotExist     ErrId = 600
	ErrId_WeaponLevelMax     ErrId = 601
	ErrId_WeaponStarMax      ErrId = 602
	ErrId_WeaponSoulExist    ErrId = 603
	ErrId_WeaponSoulNotExist ErrId = 604
	ErrId_EquipNotExist      ErrId = 605
	ErrId_EquipLevelMax      ErrId = 606
	ErrId_EquipStarMax       ErrId = 607
	ErrId_CardNotExist       ErrId = 608
	ErrId_CardWeaponNoOpen   ErrId = 609
	ErrId_CardWeaponOpened   ErrId = 610
	ErrId_CardLevelMax       ErrId = 611
	ErrId_CardWeaponEnough   ErrId = 612
	ErrId_WeaponWeared       ErrId = 613
	ErrId_EquipWeared        ErrId = 614
	ErrId_WeaponEquipEnough  ErrId = 615
	ErrId_WeaponEquipEnough1 ErrId = 616
	ErrId_WeaponNoWearEquip  ErrId = 617
)

var ErrId_name = map[int32]string{
	0:   "OK",
	1:   "UnknownError",
	2:   "UnPackError",
	3:   "SystemError",
	4:   "CustomError",
	5:   "ModelClose",
	100: "AccountExist",
	101: "AccountNotFound",
	102: "PasswordError",
	103: "KickOff",
	104: "AccountIllegal",
	105: "RoleNotOnline",
	106: "NicknameExist",
	107: "AccountTempExist",
	108: "RoleNotExist",
	109: "AccountLoging",
	200: "InstanceNotExist",
	201: "InstanceNotSingle",
	202: "InstanceNotMutli",
	203: "InstanceNotUnlock",
	300: "CreateTeamError",
	301: "TeamFullError",
	302: "TeamDismiss",
	303: "TeamInInstance",
	400: "ItemNumNotEnough",
	450: "MailNotExist",
	500: "ReqFriendEnough",
	600: "WeaponNotExist",
	601: "WeaponLevelMax",
	602: "WeaponStarMax",
	603: "WeaponSoulExist",
	604: "WeaponSoulNotExist",
	605: "EquipNotExist",
	606: "EquipLevelMax",
	607: "EquipStarMax",
	608: "CardNotExist",
	609: "CardWeaponNoOpen",
	610: "CardWeaponOpened",
	611: "CardLevelMax",
	612: "CardWeaponEnough",
	613: "WeaponWeared",
	614: "EquipWeared",
	615: "WeaponEquipEnough",
	616: "WeaponEquipEnough1",
	617: "WeaponNoWearEquip",
}
var ErrId_value = map[string]int32{
	"OK":                 0,
	"UnknownError":       1,
	"UnPackError":        2,
	"SystemError":        3,
	"CustomError":        4,
	"ModelClose":         5,
	"AccountExist":       100,
	"AccountNotFound":    101,
	"PasswordError":      102,
	"KickOff":            103,
	"AccountIllegal":     104,
	"RoleNotOnline":      105,
	"NicknameExist":      106,
	"AccountTempExist":   107,
	"RoleNotExist":       108,
	"AccountLoging":      109,
	"InstanceNotExist":   200,
	"InstanceNotSingle":  201,
	"InstanceNotMutli":   202,
	"InstanceNotUnlock":  203,
	"CreateTeamError":    300,
	"TeamFullError":      301,
	"TeamDismiss":        302,
	"TeamInInstance":     303,
	"ItemNumNotEnough":   400,
	"MailNotExist":       450,
	"ReqFriendEnough":    500,
	"WeaponNotExist":     600,
	"WeaponLevelMax":     601,
	"WeaponStarMax":      602,
	"WeaponSoulExist":    603,
	"WeaponSoulNotExist": 604,
	"EquipNotExist":      605,
	"EquipLevelMax":      606,
	"EquipStarMax":       607,
	"CardNotExist":       608,
	"CardWeaponNoOpen":   609,
	"CardWeaponOpened":   610,
	"CardLevelMax":       611,
	"CardWeaponEnough":   612,
	"WeaponWeared":       613,
	"EquipWeared":        614,
	"WeaponEquipEnough":  615,
	"WeaponEquipEnough1": 616,
	"WeaponNoWearEquip":  617,
}

func (x ErrId) Enum() *ErrId {
	p := new(ErrId)
	*p = x
	return p
}
func (x ErrId) String() string {
	return proto.EnumName(ErrId_name, int32(x))
}
func (x *ErrId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrId_value, data, "ErrId")
	if err != nil {
		return err
	}
	*x = ErrId(value)
	return nil
}

func init() {
	proto.RegisterEnum("api.ErrId", ErrId_name, ErrId_value)
}
