// Code generated by protoc-gen-go.
// source: innerMsg.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

*/
package api

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type InnerMsg struct {
	TokenId          *int64  `protobuf:"varint,1,opt,name=tokenId" json:"tokenId,omitempty"`
	SrcServerName    *string `protobuf:"bytes,2,opt,name=srcServerName" json:"srcServerName,omitempty"`
	DstServerName    *string `protobuf:"bytes,3,opt,name=dstServerName" json:"dstServerName,omitempty"`
	Msg              []byte  `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InnerMsg) Reset()         { *m = InnerMsg{} }
func (m *InnerMsg) String() string { return proto.CompactTextString(m) }
func (*InnerMsg) ProtoMessage()    {}

func (m *InnerMsg) GetTokenId() int64 {
	if m != nil && m.TokenId != nil {
		return *m.TokenId
	}
	return 0
}

func (m *InnerMsg) GetSrcServerName() string {
	if m != nil && m.SrcServerName != nil {
		return *m.SrcServerName
	}
	return ""
}

func (m *InnerMsg) GetDstServerName() string {
	if m != nil && m.DstServerName != nil {
		return *m.DstServerName
	}
	return ""
}

func (m *InnerMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *InnerMsg) SetTokenId(value int64) {
	m.TokenId = proto.Int64(value)
}

func (m *InnerMsg) SetSrcServerName(value string) {
	m.SrcServerName = proto.String(value)
}

func (m *InnerMsg) SetDstServerName(value string) {
	m.DstServerName = proto.String(value)
}

func init() {
}
